name: dotfiles
on: push

jobs:
  osx:
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.3.2
      - name: Cache homebrew packages
        uses: actions/cache@v2
        env:
          cache-name: cache-installed-packages
        with:
          path: |
            $HOME/Library/Caches/Homebrew
            /Library/Caches/Homebrew
            $HOME/.pyenv
          key: homebrew-${{ runner.os }}
          restore-keys: |
            homebrew-${{ runner.os }}
      - name: Upgrade homebrew
        run: cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
      - name: Remove problematic 2to3 bin
        run: rm /usr/local/bin/2to3
      - name: Run install.sh
        run: ./install.sh
